### ISSUE TITLE
Using Mouse.position with StartApp

### ISSUE THREAD

**Issue by aklaing** [evancz/start-app#12]
Problem instance in discussion: https://groups.google.com/forum/#!topic/elm-discuss/Ro4C6moKD0k

A proposed solution is at https://github.com/aklaing/start-app

After some discussion I can create a pull request if this is a change you would be willing to consider.
It is a breaking change, so it is possible to use default arguments (feeds = []) to make it a non-breaking change that would be great.  I would also update the documentation (README.md) to reflect this change, but waiting for your comments first.

**Comment by evancz** [comment]
Should be something like this in the new `StartApp` module in 2.0.0. Thanks for reporting this and proposing a fix!

**Comment by aklaing** [comment]
Thank you -- I saw the new StartApp discussion and the code, and it does
solve the problem nicely.
Best regards,
Ambrose
