### ISSUE TITLE
Expose `model`, e.g. for `setStorage`

### ISSUE THREAD

**Issue by chendrix** [evancz/start-app#14]
If you were to try to port [TodoMVC](https://github.com/evancz/elm-todomvc/blob/master/Todo.elm) to use `StartApp`, you'd run into a problem

```elm
port setStorage : Signal Model
port setStorage = model

model : Signal Model
model =
  Signal.foldp update initialModel actions.signal
```

the `foldp`'ed Signal that represents the state of the app is not exposed via StartApp, so you cannot use it in your port.

This signal should be exposed by `StartApp` so it can be consumed by other libs.

That way, you could do

```elm
app =
  { model = initialModel, view = view, update = update }

main =
  StartApp.start app

port setStorage : Signal Model
port setStorage = StartApp.model app
```

**Comment by evancz** [comment]
There are many things start-app cannot do, but that is intentional. The goal is to provide the most simple API possible that can still start your app. I don't want to add more to it at this time.

When people reach the limitations they need to switch to using signals directly for now.

**Comment by chendrix** [comment]
Is providing TodoMVC using the StartApp not a worthwhile pedagogical goal?

The diff is minor

```
Comparing evancz/start-app 1.0.1 to local changes...
This is a MINOR change.

------ Changes to module StartApp - MINOR ------

    Added:
        actions : Signal.Mailbox (Maybe.Maybe a)
        state : StartApp.App model action -> Signal.Signal model
```

I can tell you personally that hearing `StartApp` touted as an example of how to instantly craft a "well architected" app and then having only the most basic of examples on how to use it, while having all of the complex architectures and other examples still use raw Signals was frustrating.

**Comment by evancz** [comment]
I know, we are working on a more robust version that covers all the cases well. Lots of folks run into issues when they get to signals. I'm not saying "this is not important", it is super important. I am saying "I think we have a better way" and we are working on it.

**Comment by evancz** [comment]
Sorry if this sounds curt :( I very much appreciate the PR!

Can improve how things are phrased in the readme? My goal with start-app was always to get people started quickly, not to solve everything. My major development push is trying to generalize the core concept of start-app in such a way that we can cover everything a normal app would need, including effects and sending messages out of components. This is stuff that has not been clearly outlined anywhere yet. Lot's of folks are asking for this in lots of different forums, and it's coming!
