### ISSUE TITLE
The readme doesn't actually help me to get started

### ISSUE THREAD

**Issue by 0xR** [evancz/start-app#15]
I want to get started using ELM on my local machine. So installed this start-app, but I have no clue how to run it. How do I start my web server? This should be in the readme.

**Comment by dmvaldman** [comment]
:+1:

**Comment by ParkinT** [comment]
There is no need for a web server.  Part of the 'magic' of this is that it [can] create a stand-alone HTML file with embedded Javascript.

After following the instructions **currently in the README** {which may require, first, the installation of elm-lang/core}
>elm-package install evancz/start-app
elm-package install evancz/elm-html

Simply copy and paste this entire code block (from within the README) to a file with the ".elm" extension(i.e start-test.elm)

```elm
import Html exposing (div, button, text)
import Html.Events exposing (onClick)
import StartApp

main =
  StartApp.start { model = model, view = view, update = update }

model = 0

view address model =
  div []
    [ button [ onClick address Decrement ] [ text "-" ]
    , div [] [ text (toString model) ]
    , button [ onClick address Increment ] [ text "+" ]
    ]

type Action = Increment | Decrement

update action model =
  case action of
    Increment -> model + 1
    Decrement -> model - 1
```

Finally, use this command to *compile* the file into a single, stand-alone HTML file.
`$ elm make start-test.elm --output index.html`
And then just open it in a browser:
`$ open -a safari index.html`

---

I agree this should be part of the README.

**Comment by 0xR** [comment]
To make people more impressed by elm I would recommend letting the readme say something like this:

1. Make sure you have set up your ELM_HOME environment variable.
2. Inside your project directory run `elm-reactor`
3. Browse to http://localhost:8000
4. Click the wrench icon next to `start-test.elm`
5. Check the swap checkbox by making it blue

Now each time you edit `start-test.elm` and save it will be automatically loaded in your running browser. The state of your application is preserved.

**Comment by evancz** [comment]
Closing in favor of #8 which is about the same stuff. Planning to fix the readme today!
