### ISSUE TITLE
The example doesn't have type anotations

### ISSUE THREAD

**Issue by 0xR** [evancz/start-app#16]
I am new to elm, and I am confused by the all the type inference that is probably going on. Having type annotations in the example would help a lot. Especially since most of it is also in the architecture guide @ http://elm-lang.org/guide/architecture.

Here is what I came up with. I think there is no type inference magic left.

```elm
import Html exposing (div, button, text, Html)
import Html.Events exposing (onClick)
import StartApp

main : Signal Html
main =
  StartApp.start { model = model, view = view, update = update }

type alias Model = Int
model : Model
model = 0

view : Signal.Address Action -> Model -> Html
view address model =
  div []
    [ button [ onClick address Decrement ] [ text "-" ]
    , div [] [ text (toString model) ]
    , button [ onClick address Increment ] [ text "+" ]
    ]

type Action = Increment | Decrement

update : Action -> Model -> Model
update action model =
  case action of
    Increment -> model + 1
    Decrement -> model - 1
```

**Comment by ParkinT** [comment]
Great job.  I agree.
:+1:

**Comment by evancz** [comment]
Thanks for letting me know about your experience!

I kind of want to show off that you do not need type annotations for folks that are totally new, and then guide them to resources that introduce those concepts in a nice way. I don't know what the right thing to do here is really though, so I am going to close for now and search for more perspectives on this.

**Comment by evancz** [comment]
I'm thinking it'd be good to put a note in the architecture tutorial like "if you are new to types, check out this document"

Would that help make the learning path smoother?

**Comment by 0xR** [comment]
That might help, but you could also turn it around and having types by default and another doc without the types. The types do make te code easier to understand. I doubt people getting started with elm are against type annotations. Haskell people understand and javascript people are not looking at elm if they aren't interested in static typing.

But that's just my 2 cents.

The link to the doc with types is already better than before.

**Comment by ParkinT** [comment]
Let me offer a compromise to this dilemma.

If you call `make` with the `--warn` flag the type-annotations are spelled out for you.  Just mention this in the docs.
Then **everyone** can be happy.

**Comment by 0xR** [comment]
@ParkinT Wow that is really useful, I didn't know that was possible. Mentioning that also helps.

**Comment by evancz** [comment]
Yeah, I should recommend folks using `--warn` more, had not thought of it as a teaching tool to see those annotations. Great suggestion!

How do you feel about mentioning this in the Elm Architecture tutorial guide to running the file though? Or maybe linking directly to [here](https://github.com/evancz/elm-architecture-tutorial/tree/master/examples/1) which explains how to run it locally.

**Comment by ParkinT** [comment]
I like the idea of mentioning it as part of the Elm Architecture tutorial.  In a "and if you use this switch you can always be reminded of the type annotations inferred..." manner.

Thanks @0xR and @evancz for the kudo.
