### ISSUE TITLE
Example does not work for me

### ISSUE THREAD

**Issue by stedi67** [evancz/start-app#18]
The example for start-app does not work for me.
I'm on a recent Ubuntu 64 bit system and installed elm-platform via npm.
When trying to compile the example (copy and pasted from the README), I get the following error:

```
$ elm make example.elm --output index.html
## ERRORS in example.elm #######################################################

-- TYPE MISMATCH --------------------------------------------------- example.elm

The 1st argument to function `start` has an unexpected type.

6|   StartApp.start { model = model, view = view, update = update }
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    (number, Effects.Effects Action)

    number


Detected errors in 1 module.         
```

`elm make`: `elm-make 0.2 (Elm Platform 0.15.1)`

What did I do wrong?

**Comment by ThomasWeiser** [comment]
I guess you mixed an old example (maybe from a former version of *The Elm Architecture* or the README) with the recently updated version of start-app. Both repos/packages have been updated recently. (They now include Effects, which are mentioned in the error message.)

@evancz: Version 2.0.0 of start-app is published here only through the tag 2.0.0, but not in any branch, which may be confusing if someone is looking up the new code on github instead of on the package site.

**Comment by stedi67** [comment]
Hmm, I was just doing the installation step by step as described in the readme (`https://github.com/evancz/start-app/blob/master/README.md`).
Is the installation instruction not complete or is the first eample in that readme wrong?
@ThomasWeiser: based on your comment I could imagine that the npm elm-platform installer could be too old, but so far, I had no luck to compile everything from source...

**Comment by ThomasWeiser** [comment]
Ok, the example in the Readme is not updated to v2.0.0 of start-app.
To use the old version: Start in a fresh directory and change the first steps to:

```sh
elm-package install evancz/start-app 1.0.0
elm-package install evancz/elm-html
```

**Comment by stedi67** [comment]
Now I get it. When installing as described, one installs version 2.0
The real fix would be to merge tag 2.0 into master and using StartApp.Simple instead of StartApp in the example.

**Comment by ThomasWeiser** [comment]
Yep

**Comment by evancz** [comment]
Gonna do that today, thanks for the report!
