### ISSUE TITLE
First value of inputs is ignored

### ISSUE THREAD

**Issue by jinjor** [evancz/start-app#19]
I tried start-app@2.0.0 and found that the first value of the `inputs` is ignored.

Here is an example.
```elm
init : (Model, Effects Action)
init =
  (,) {
  , dimensions = (0, 0) -- this is dummy
  } Effects.none

app =
  StartApp.start
    { init = init
    , update = update
    , view = view
    , inputs =
      [ Signal.map Dimensions Window.dimensions ]
    }
```
I don't know the first value of `dimensions` so I need to put a dummy, but the dummy value is used until new dimensions come.
I think using `Signal.Extra.foldp'` may solve it, and then `init` should be `Action -> (Model, Effect Action)`, but I'm not sure how API should actually be because not all signals have the first value.

**Comment by evancz** [comment]
I know about this issue and have some ideas to fix it. Don't want to track this here though. Thank you for the report!

**Comment by sgronblo** [comment]
I really enjoy Elm so far but this issue is very annoying. Is there any update? Why don't you wanna track it here? Is it being tracked somewhere else instead?

**Comment by tomekwi** [comment]
@sgronblo, @seanhess has been working on resolving this in https://github.com/evancz/start-app/pull/37. It helped me a lot!

**Comment by seanhess** [comment]
@sgronblo @tomekwi Note that I can't really resolve the issue, since there's no interest from the maintainers in merging that pull request, but if you need this functionality you can use my fork as a workaround.

**Comment by tomekwi** [comment]
Thanks! That’s exactly what I did at https://github.com/magnificat/magnificat.surge.sh.
