### ISSUE TITLE
Having an AJAX response update `actions`?

### ISSUE THREAD

**Issue by srid** [evancz/start-app#2]
The `actions` mailbox defined *inside* [the `start` function](https://github.com/evancz/start-app/blob/master/src/StartApp.elm#L84) cannot be accessed outside, and as such I'm wondering how to trigger an update in the view using the data that comes from an AJAX request (which itself was triggered by defining a port)?

**Comment by srid** [comment]
FWIW, my currently solution is to add a 4th field to the App type:

https://github.com/srid/chronicle/commit/fa251ef7b080cc9eb9e44978fc35358ba32a7577

I can't say if there is a better way as I'm still getting a hang of Elm.

**Comment by evancz** [comment]
Before this library existed, everyone wired things together themselves as you are doing, without any sort of `start` function. I would check out [this example](http://elm-lang.org/edit/examples/Reactive/ZipCodes.elm) to see what that looks like. It sends AJAX requests to some 3rd party zip code lookup service.

Does that help?

As an aside, this start-app package is intended to insulate people from signals for as long as possible. The idea is that you can get a really easy learning curve. It sounds like this is the tipping point where it makes sense to start using signals directly.

**Comment by srid** [comment]
In that example I see that `query` and `results` mailboxes are global variables, and is similar to my solution in https://github.com/srid/chronicle/commit/fa251ef7b080cc9eb9e44978fc35358ba32a7577 where I extracted the `actions` local variable outside of `start` (and inside the `App` record) and let it be accessible from the main port (a side benefit of it is to get rid of the Maybe type as I have a 'default'  action value defined in Controller.elm).

I didn't realize that `start-app` can be used a package. Elm is pretty nice; fixing type errors takes a while, but after that app runs magically (no runtime errors?!?!).

**Comment by evancz** [comment]
Yeah, once you get into the swing of things it's pretty crazy to have no runtime errors :) I have some fixes in the works that make the error messages [a ton better](https://groups.google.com/forum/#!topic/elm-discuss/8DQlngkkK00) so hopefully that barrier will start to feel lower once that comes out.

Do you think this issue is okay to mark as resolved? If not, how can I help more?

**Comment by srid** [comment]
I feel this issue need not remain open. However, as a suggestion for future, it may be worth creating a 'FAQ' where questions like this (pulling data on initial page load) are answered using recommended code implementation.
