### ISSUE TITLE
StartApp needs a way to deal with required initial value of a signal

### ISSUE THREAD

**Issue by pdamoc** [evancz/start-app#21]
The simplest example would be something that properly displays the window dimensions.
The following minimal code shows the issue (width display starts wrong but works as expected after the first resize) 
https://gist.github.com/pdamoc/06edd378b2af86a99f9d

Signal.Extra.foldp' might be part of the solution. 
https://groups.google.com/forum/#!topic/elm-discuss/h-WAC3kgrOU

**Comment by jinjor** [comment]
See #19, the same :)

**Comment by pdamoc** [comment]
Ooops.... duplicate. :) 
Thanks jinjor!
