### ISSUE TITLE
Time.timestamp integration

### ISSUE THREAD

**Issue by z5h** [evancz/start-app#24]
I imagine several apps that would need to know when an Action was triggered.
If there is an easy way to use `Time.timestamp` with `StartApp` then it's not clear to me.

It seems fairly straightforward to copy `StartApp` to `TimeStampedStartApp` or whatever the case may be, and require `update` to have the signature `update : (Time, Action) -> Model -> Model`. 

In `start` `Time.timestamp` would need to be used appropriately.

Does this make sense, and have a place in start-app? Or is this outside of the scope of start-app or better achieved a different way?

**Comment by z5h** [comment]
Please see this Gist as an example. 
Happy to create a pull request that adds it if it makes sense.

https://gist.github.com/z5h/41ca436679591b6c3e51

**Comment by amitaibu** [comment]
@zh5 [here's](https://github.com/Gizra/elm-hedley/commit/50d3ac1248423d4ffcb047cacc0b6d5432e52c2c#diff-c6258c702028b4bdfac823248535c07cR429) an example where just a specific action gets the timestamp, without change to start-app

**Comment by z5h** [comment]
@amitabu it looks like it gets the data from the server. Perhaps I'm mistaken. I'd like to get a timestamp for any action. Let's assume no server.

**Comment by amitaibu** [comment]
> it looks like it gets the data from the server. 

No, the flow is - fetch data from the server `andThen` get the current timestamp.

[Here's](https://github.com/Gizra/elm-hedley/commit/86e028464b04b1f37efe7c1d55a61e1ae18eae17#diff-c6258c702028b4bdfac823248535c07cR422) the follow up commit, that checks the cache is still valid. You can see we are getting the current timestamp there as-well, and compare it with the previous one.

**Comment by z5h** [comment]
@amitaibu ah, so this is a Task, and requires creating a task to get the time. Is that right? With my solution you simply get the time with any action. No need for tasks.

**Comment by amitaibu** [comment]
Yeah, I guess both solutions are valid :) I needed the timestamp only in a single action.

**Comment by metaraine** [comment]
I would also appreciate a version of StartApp that passed the time to update.

**Comment by evancz** [comment]
Things are different with 0.17
