### ISSUE TITLE
Dreamwriter runtime error record

### ISSUE THREAD

**Issue by mr-bo-jangles** [evancz/start-app#25]
looks like you need to update the readme, https://github.com/rtfeldman/dreamwriter/issues/49

**Comment by evancz** [comment]
This issue does not provide enough information for me to do something. I can't go on a link hunt on every issue. Can you explain the problem here in a self contained way, potentially indicating which part of the readme specifically with a link?

**Comment by mr-bo-jangles** [comment]
You claim Dreamwriter has never had a Runtime exception at the very bottom your Readme.md

I'm pointing to an issue where that is shown to now be incorrect.

**Comment by evancz** [comment]
I'd like to see a resolution on whether the error is in elm code or JS code. Since it involves the full screen API, @rtfeldman is definitely using a port to talk to some JS. My money is on a JS problem.

**Comment by rtfeldman** [comment]
Oh that's 100% a JS problem. See https://github.com/rtfeldman/dreamwriter/issues/49#issuecomment-137570551

**Comment by rtfeldman** [comment]
Note that the Readme says (accurately) that Dreamwriter's **Elm code** has never had a runtime exception. Elm is awesome, but nothing is awesome enough to fix JavaScript. :stuck_out_tongue_winking_eye:

**Comment by mr-bo-jangles** [comment]
Lol, typical.. when it all comes down to it JS is the cause of all of life's problems :p
