### ISSUE TITLE
Approaches to integrating with start-app

### ISSUE THREAD

**Issue by rgrempel** [evancz/start-app#29]
Since start-app is such a nice starting point for app development, it's natural, when writing another module, to want to be able to integrate with start-app in a nice way. That is, it's nice to make it easy for your module to be used in conjunction with start-app. I've run into a bit of a puzzle doing that, which leads to both a specific and a general question.

The background (which I'll try not to dwell on) is that I'm working on a module to help with single-page-app routing of the location hash -- where the "routing" goes in both directions -- that is, where changes to your model may generate changes to the browser's location hash, and changes to the browser's location hash may generate actions within your app. (So, this builds on [TheSeamau5/elm-history](http://package.elm-lang.org/packages/TheSeamau5/elm-history/latest) and is related to [TheSeamau5/elm-router](http://package.elm-lang.org/packages/TheSeamau5/elm-router/latest), but has somewhat different goals).

Now, the implementation is, of course, more complex than this, but what my module ultimately provides (conceptually) is two things.

*  `History.hash -> Signal action`

That is, we wire up the signal graph so that changes to the browser's location hash are mapped to actions your app performs.

*  `Signal model -> Signal (Task () ())`

Where changes to your model are mapped to changes to the browser's location hash.

Now, it turns out to be important that these two things are inter-related, in the sense that we need to avoid infinite loops -- that is, we need to avoid a situation where changing the model triggers a change to the location hash, which in turn triggers a change to the model, *ad infinitum*. That's not hard to avoid, but it does mean that the two things the module provides are inter-related -- that is, they can't be done entirely separately -- they are generated together.

So, how to nicely integrate this with start-app? Now, each of these things are easy to integrate with start-app if handled separately. One of the things which `StartApp.start` provides is the `Signal model`, so I can suggest using that as input to my module. And, one of the things which `StartApp.start` takes as a parameter is `inputs : List (Signal action)`, so I can suggest supplying what my module provides as part of that list.

However, you may have spotted the chicken-and-egg problem already. In order to produce the `Signal action`, my module needs the `Signal model`. However, in order to get the `Signal model` from `StartApp.start`, my module needs to provide the `Signal action` as a parameter. So, it won't work -- and I'm pretty sure that this is a necessary consequence of what I'm trying to achieve.

Now, one way to untie the knot would be for start-app to expose the `Mailbox action` which it creates internally. If that were available as part of the result of `StartApp.start`, then it would be possible to send the actions generated by my module to that address, without the chicken-and-egg problem.

So, I suppose the specific question I have is whether start-app might consider exposing its `Mailbox action`. Now, I should say that there may be perfectly sound reasons why start-app doesn't want to do that -- I can imagine what some of those reasons might be.

The more general question is how module authors ought to think about start-app. Should we treat start-app as, well, a starting point, that people might move beyond fairly readily, if needed? Or, should we try really hard to maintain integration with start-app, including suggesting changes to start-app if that's needed? I should say that I'm not advocating one way or the other -- I can see plausible reasons for either approach.

**Comment by rgrempel** [comment]
The module I mentioned above is now published, in case anyone is interested.

https://github.com/rgrempel/elm-route-hash

However, I should make it clear that this issue isn't primarily about the details of that module. It's more a question of how module authors ought to think about start-app in general -- that is, to what lengths ought we go in order to integrate with start-app (vs. asking users to move beyond start-app when needed).

**Comment by rgrempel** [comment]
Just to follow up with a little more context, here are the specific changes to `StartApp` that would expose the `Address`:

https://github.com/rgrempel/elm-route-hash/commit/77228f25de1e05f419839ed9f63a51e046f84493#diff-0017ac34b434e83f80d5140dc35b727c

So, in part the question is whether a change of this type might be considered for `StartApp`. But, the wider question is what role we should envision for `StartApp` within the Elm community as it develops. That is, should we should conceive of `StartApp` as something which, in the normal course of events, developers will make local copies of and modify in a variety of ways? Or should we conceive of it as something which ideally is used unchanged?

**Comment by seanhess** [comment]
I'm confused about this too. start-app is marketed as the blessed path, but the community seems to treat it as a crutch for beginners. I'm hitting the same issue trying to implement `elm-router`. None of the examples use start app and I have no idea how to create an app without it.

**Comment by amitaibu** [comment]
FWIW, I think that start-app should indeed cater for more advanced use. We could indeed copy it and create a custom startApp, but then it forces us to keep an eye on the original one, and sync back the changes.

btw:
>  I'm hitting the same issue trying to implement elm-router

@seanhess , you should check [elm-router-hash](https://github.com/rgrempel/elm-route-hash) which has wonderful docs + examples based on start-app/ Elm architecture.

**Comment by amitaibu** [comment]
@rgrempel maybe worth creating a PR for this - so it would be easier for others to see the small changes that you suggest

**Comment by seanhess** [comment]
Thanks @amitaibu I will. I was initially turned off by having to fork start-app, and that it seemed over complicated, but I'll give it another shot.

**Comment by rgrempel** [comment]
I ended up figuring out how to make elm-route-hash work with an unmodified StartApp -- see 

https://github.com/rgrempel/elm-route-hash/commit/887b03300899600cdebab83522582a7246029d20

So, I'll close this issue -- it may still be of some general interest, but I no longer have an example that illustrates it.
