### ISSUE TITLE
access to actions (signal) outside the update function

### ISSUE THREAD

**Issue by flip111** [evancz/start-app#32]
This is really nice https://github.com/evancz/start-app/blob/master/src/StartApp.elm#L31-L33 but what about sending one of those actions to a port? Ok the actions are not valid javascript type but an easy map function can take care of that.

**Comment by evancz** [comment]
You can use the values in [here](https://github.com/evancz/start-app/blob/master/src/StartApp.elm#L58) to get that information out. One of the parts of your model can be "info I want to send to the world" and you can model it as a `Maybe` so it can be filtered or whatever. That should cover your scenario, so I am going to close. It's fine to continue discussion in this thread, and if you have specific API suggestions to cover your scenario another way, open a new issue.

**Comment by flip111** [comment]
@evancz thanks a lot, that really helps !
