### ISSUE TITLE
can't build: hGetContents: invalid argument (invalid byte sequence)

### ISSUE THREAD

**Issue by kaervin** [evancz/start-app#33]
I am trying to build the start-app, and some other of evanczs tutorials, but they won't compile.
The error I get is the following:
```
elm-make: elm-stuff/packages/evancz/virtual-dom/2.0.0/src/VirtualDom.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation
```

The workaround proposed in https://github.com/elm-lang/elm-make/issues/33 doesn't seem to work.

Downgrading the required Version of Virtual-Dom to 1.2.3 lets it compile,
(found that out after noticing that TodoMVC had no problems)
but then the same error occurs with elm-effects.

```
elm-stuff/packages/evancz/elm-effects/2.0.0/src/Effects.elm: hGetContents: invalid argument (invalid byte sequence)
```

**Comment by evancz** [comment]
This is probably an elm-make thing, not a start-app thing. What OS are you on? How did you install things? Is there anything weird about your setup? Like, is the default language Japanese or something?

**Comment by kaervin** [comment]
I am using arch linux,
LANG=en_US.UTF-8,
installed elm through npm,
and then just used elm-make in the root directory of the project.
I wouldn't say there is anything weird about my setup.

**Comment by ir4y** [comment]
+1
Same issue when i try to build it with docker
```
docker-compose build
Building elm...
Step 0 : FROM node:4.1.1
 ---> fc81e574af43
Step 1 : RUN npm install -g elm
 ---> Using cache
 ---> c1414bfd5766
Step 2 : ENV ELM_HOME /usr/local/lib/node_modules/elm/share
 ---> Using cache
 ---> f953438beea3
Step 3 : RUN mkdir /data
 ---> Using cache
 ---> 5cdc12c7bb3a
Step 4 : WORKDIR /data
 ---> Using cache
 ---> f8a03d3ce6c4
Step 5 : ADD . /data
 ---> caa78892a412
Removing intermediate container 7ff3df8e81d6
Step 6 : RUN elm-make --yes
 ---> Running in ffad7681a6e3
Downloading elm-lang/core
Downloading evancz/elm-effects
Downloading evancz/elm-html
Downloading evancz/virtual-dom
Packages configured successfully!
elm-make: elm-stuff/packages/evancz/virtual-dom/2.0.0/src/VirtualDom.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation
Service 'elm' failed to build: The command '/bin/sh -c elm-make --yes' returned a non-zero code: 1
```

I have added docker support at my fork https://github.com/ir4y/start-app

**Comment by jvoigtlaender** [comment]
@kaervin and @ir4y, note that there is more than one workaround for this issue listed at https://github.com/elm-lang/elm-make/issues/33. Maybe one of them helps in your cases?

**Comment by ir4y** [comment]
Thank you @jvoigtlaender
It is a locale issue. Reconfigure locale to C.UTF-8 fidex it.

**Comment by evancz** [comment]
It is my understanding that this is not an issue on the code here, so I am going to close. If I am wrong, lets continue here describing what exactly is going on in start-app or figure out where the issue *should* be opened.
