### ISSUE TITLE
Semantics broken due to unfair merging

### ISSUE THREAD

**Issue by jvoigtlaender** [evancz/start-app#38]
Consider this program:
```elm
import StartApp
import Effects
import Html
import Mouse

main =
  app.html

inp1 =
  Signal.map (always ((+) 1)) Mouse.clicks 

inp2 =
  Signal.map (always ((+) 2)) Mouse.clicks 

app =
  StartApp.start
    { init = (0, Effects.none)
    , update = \f i -> (f i, Effects.none)
    , view = \_ -> Html.text << toString
    , inputs = [ inp1, inp2 ] }
```
Now consider the same program with the last line replaced by:
```elm
    , inputs = [ inp2, inp1 ] }
```
There is nothing in the documentation of the package (or in the Elm Architecture Tutorial) that suggests the two programs should behave different from each other. But they do.

The first program increases the displayed counter by `1` on each mouse click. The second program instead increases the counter by `2` on each mouse click. The only sensible semantics I can see for this program (while maintaining modularity as is the aim of the Elm Architecture) is to increase the counter by `3` on each mouse click.

That can be made to happen by replacing [this line](https://github.com/evancz/start-app/blob/2.0.2/src/StartApp.elm#L105) in the `start-app` implementation by the following:
```elm
List.foldl
  (Signal.Extra.fairMerge List.append)
  messages.signal
  (List.map (Signal.map singleton) config.inputs)
```
where `Signal.Extra.fairMerge` is from http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.6.0/Signal-Extra.

@evancz, is this motivation enough to add something like `fairMerge` to `core`? I think either that has to happen, or alternatively, `start-app` here could define it internally.

(Note: Adding `fairMerge` to `core` would allow a better implementation for it than the one in `elm-signal-extra`, because `Native/Signal.js` in `core` already contains a `genericMerge` implementation that would only need to be exposed.)

**Comment by jvoigtlaender** [comment]
(Message on the mailing list reminded me of this:)

@evancz, I don't know whether you have seen this before. Do you agree that this is a bug in `start-app` that should be fixed? (How to fix it is detailed above.)

**Comment by jvoigtlaender** [comment]
A case "in the wild" (rather than my artificial example above) where the order of elements in `inputs` becomes an issue while it shouldn't, and isn't documented in `start-app` to be relevant: https://github.com/w0rm/elm-unsoundscapes/blob/650d754f53334906240de6d3b4c2b8664a6ed418/Unsoundscapes.elm#L126

**Comment by jvoigtlaender** [comment]
@evancz, I still think this is a pretty bad bug here in `start-app`. If I were to write a pull request fixing it, that would involve copying [this function](https://github.com/Apanatshka/elm-signal-extra/blob/5.7.0/src/Signal/Extra.elm#L380-L391) over, would you even consider merging it?

**Comment by ritcoder** [comment]
This also gave me some issues not long ago. I had copy the startapp file to my project and replace the function. 

@evancz Any idea when this update will be done?

**Comment by jvoigtlaender** [comment]
Here's an alternative suggestion: Replace the `inputs : List (Signal action)` field in `type alias Config model action` by something of type just `Signal action`. Then users relying on more than one input signal there will have to use something like `Signal.merge` or `Signal.mergeMany` themselves, in which case they will explicitly have to confront the issue of order and conflict (and contrary to the current `start-app` documentation, the `Signal.merge`/`Signal.mergeMany` documentation already tells them that update events may be dropped).
