### ISSUE TITLE
How to use Debug.watch with Startapp.Simple?

### ISSUE THREAD

**Issue by ccorcos** [evancz/start-app#41]
How do I watch the model or action signal?

http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Debug#watch

And speaking of, what deos `<~` mean? I can't find that syntax in the docs

http://elm-lang.org/docs/syntax

**Comment by rgrempel** [comment]
`<~` was in the `Signal` module in Elm 0.15, but was removed in Elm 0.16.

If you want to see what it did, it can now be found here:

http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.7.0/Signal-Extra#<~

**Comment by ccorcos** [comment]
Oh man. Thats crazy! Really cool how you can make your own operators like that though.

So I altered the startapp code to return all 3 signals.

```
start : Config model action -> {html : Signal Html, action : Signal (Maybe action), model : Signal model}
start config =
  let
    actions =
      Signal.mailbox Nothing

    address =
      Signal.forwardTo actions.address Just

    update maybeAction model =
      case maybeAction of
        Just action ->
            config.update action model

        Nothing ->
            Debug.crash "This should never happen."

    model =
      Signal.foldp update config.model actions.signal
  in
    { html = Signal.map (config.view address) model
    , action = actions.signal
    , model = model
    }
```

But I still cant figure out how to map the signal to `Debug.watch`

```elm
app = 
  start
    { model = 10
    , update = update
    , view = view
    }

Signal.map (Debug.watch "model") app.model
```

I get this error:

```
I ran into something unexpected when parsing your code!

14│ Signal.map (Debug.watch "model") app.model
          ^
I am looking for one of the following things:

    a pattern
    an equals sign '='
    more letters in this name
    whitespace

```

**Comment by rgrempel** [comment]
Is that snippet literally what you are using? If so, then you don't really have a context for the `Signal.map` ... you would want something like:

```elm
anotherSignal =
    Signal.map (Debug.watch "model") app.model
```

**Comment by jvoigtlaender** [comment]
As an aside: I made a pull request to `core` (https://github.com/elm-lang/core/pull/450), making sure that the now non-existing operator `<~` is no longer used in example code.

**Comment by ccorcos** [comment]
@rgrempel I tried both, and it still doesn't work. It says I don't have any watches. Hot Swapping doesnt appear to be working either, and I get this error when press I restart as well (documented in another issue ticket https://github.com/elm-lang/elm-reactor/issues/168)

**Comment by rgrempel** [comment]
Hmm. I don't use elm-reactor much myself, so I'm not that familiar with how watches work. 

One issue might be this. The Elm runtime trims the signal graph to remove signals that aren't being used. Thus, it may be that creating a new signal just to add a watch might be useless -- it might just be trimmed, so that the watch will never happen. 

To avoid that, you might have to add the watch inside your update function itself --  that is, at the very point that you produce the new model. 

But that may be entirely on the wrong track.

**Comment by jvoigtlaender** [comment]
@ccorcos, do you still need help with this?

**Comment by ccorcos** [comment]
I never figured it out, but I'm not using reactor anymore so I'll close it
