### ISSUE TITLE
README has link to "full documentation" that takes you back to README

### ISSUE THREAD

**Issue by proehlen** [evancz/start-app#44]
Under "Further Learning" in the README is a sentence with a link: "Check out the full documentation for this library here.".  The link at here is to http://package.elm-lang.org/packages/evancz/start-app/latest/.  That page, as near as I can tell is identical content to the README even down to repeating the link to the "full documentation" which, now, is itself.

Apart from logging potential issue this I'm interested if there is any more documentation to start-app somewhere and, if so, could I have a link?

**Comment by jvoigtlaender** [comment]
The point of that link is that if you follow it, you have links to the specific modules on the right. These are not part if the README on GitHub. Is that content enough for your documentation needs?

**Comment by proehlen** [comment]
Ok thanks.  Didn't notice the modules links.  Just got thrown by the loop back. 

I've read the modules links now and if that's all there is then that's ok.  Thanks.
