### ISSUE TITLE
Missing key information

### ISSUE THREAD

**Issue by chasm** [evancz/start-app#8]
As with many if not most tutorials/examples, we tend to forget the things we take for granted.

The README asks me to download and install the app. Then it gives me some code, and, oddly, tells me to run it online. Why did I download the starter app if I was going to do that?

No doubt this same code will work in my starter app, but _where does it go?_ And what is the proper file naming protocol?

I recommend that when you put together examples such as this, you show them to a programmer friend who is not familiar (or barely familiar) with Elm and then see where she struggles with the instructions. 

After all, the purpose of the exercise is to encourage newbies to learn Elm, right? It's a bit self-defeating to lose a significant percentage because they gave up after a short struggle because some simple, easy, but key piece of information was missing.

**Comment by Pholey** [comment]
:+1:

**Comment by cserb** [comment]
second that

**Comment by ParkinT** [comment]
Perhaps [this](https://github.com/evancz/start-app/issues/15) is a bit helpful.

**Comment by evancz** [comment]
Thanks for pointing this out! I just published a new readme should guide people in a better way.

Please open a new issue if there are things that can be further improved!
